### ISSUE TITLE
Apple trees not grindable

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#376]
From *julix8ms*

```
I made a common tree grinding generator based on the fact that you should be able to grind apple trees, but it doesn't work. Can you make it work? Or, if you blocked it, why?
```

**Comment by OgelGames** [comment]
Apparently group recipes don't work with technic : https://github.com/pandorabox-io/technic/blob/5069207e71e91d0ce162067cfda6a71abe77e779/technic/machines/register/grindings.lua#L51

**Comment by thomasrudin** [comment]
fixed!
Reference: https://github.com/h-v-smacker/technic/blob/master/technic/machines/register/grindings.lua

**Comment by OgelGames** [comment]
Not quite fixed:
```
2019-12-16 20:43:49: ERROR[Main]: generateImage(): Could not load image "technic_tree_grindings.png" while building texture; Creating a dummy image
2019-12-16 20:43:49: ERROR[Main]: generateImage(): Could not load image "technic_tree_grindings.png" while building texture; Creating a dummy image
```
Working on a fix right now, also going to add support for `moretrees` while I'm there :wink:

**Comment by OgelGames** [comment]
All fixed now 😄

**Comment by thomasrudin** [comment]
Thanks a lot :+1: (wow, we have quite a few tree types... :open_mouth:)
