### ISSUE TITLE
Removable korlen travelboxes

### ISSUE THREAD

**Issue by kubaorlen** [pandorabox-io/pandorabox.io#390]
Add option to remove `korlen` travelboxes on `protected areas` owned by another players.

**Additional note:**
No way to remove `korlen` travelboxes on `open` and `free` areas.

**Comment by OgelGames** [comment]
I thought this was fixed here: https://github.com/pandorabox-io/pandorabox.io/issues/368#issuecomment-566048267 😕

**Comment by kubaorlen** [comment]
I tested it, another players still can't remove my travelboxes on theirs areas :(

**Comment by thomasrudin** [comment]
@kubaorlen the base-work is done for that, but the `travelnet` mod needs to updated for this to work (the additional `pos` parameter here: https://github.com/pandorabox-io/pandorabox_custom/commit/ca01095b1d7c2a9210de857aa1ec329dc8816ec7#diff-a9ca2807fc89edbc2d9729cdac9f221bL7)

Currently there are some issues with the forked `travelnet` repo, like removal of stations when visiting them... :confused:

**Comment by thomasrudin** [comment]
Opened again with #393
