### ISSUE TITLE
tpr crash

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#401]
```
2020-01-05 14:41:17: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod '' in callback on_chat_message(): /data/world//worldmods/tpr/init.lua:146: attempt to index a nil value
2020-01-05 14:41:17: ERROR[Main]: stack traceback:
2020-01-05 14:41:17: ERROR[Main]: 	/data/world//worldmods/tpr/init.lua:146: in function 'func'
2020-01-05 14:41:17: ERROR[Main]: 	/usr/local/share/minetest/builtin/game/chat.lua:55: in function </usr/local/share/minetest/builtin/game/chat.lua:34>
2020-01-05 14:41:17: ERROR[Main]: 	/usr/local/share/minetest/builtin/game/register.lua:429: in function </usr/local/share/minetest/builtin/game/register.lua:413>
```

**Comment by thomasrudin** [comment]
reported here: https://github.com/ChaosWormz/teleport-request/issues/23 and reverted here: https://github.com/pandorabox-io/pandorabox-mods/commit/d249defb4b97b6c9abfaf139d6115817af87298d

**Comment by Panquesito7** [comment]
Tested and works; fixed in commit [`4102b5f`](https://github.com/ChaosWormz/teleport-request/commit/4102b5f0fe892cc32c5ad20be08cfc10869f3d2d).

**Comment by SwissalpS** [comment]
indentation is wonky. confusing to read.

**Comment by coil0** [comment]
That commit does not fix the issue. It still crashes if you send a request to a nonexistent player.

**Comment by Panquesito7** [comment]
> That commit does not fix the issue.

Fixed.

**Comment by thomasrudin** [comment]
lets try this again: https://github.com/pandorabox-io/pandorabox-mods/pull/297 ... :confounded:
